### ISSUE TITLE
body check

### ISSUE THREAD

**Issue by genechan** [littlebits/cloud-api-lessons#1]
Hi,
First, thanks for posting your code :)

When i was working with it I found that Heroku will error then crash. I found that when using the button and sound sensor I was not getting any post body data, so the request.on(data) will never get called.

If you put a bodyString check before calling the handleCloudbitEvent() call it will prevent Heroku from crashing.

I was wondering which input sensor you use that got you the post data to work?

Thanks

**Comment by stresslimit** [comment]
Thanks for commenting; this was working with any given input, but you've made me wonder and want to go check again.

I'll do some digging and get back to you in the next few days. Thanks for much for reaching out!

**Comment by jasonkuhrt** [comment]
@genechan You're welcome! Our pleasure : )

There is another issue that has come to our attention and we're thinking this could be related. I'll try investigating this weekend too.

**Comment by guipena** [comment]
Hello, I've been working with genechan on this and it looks like we're still having this issue on trying to connect the cloudbit with our heroku app. 

Do you know if there is anything we can do from our end or could you please let me know once this issue is solved?

We appreciate your support. 

Thanks , Guilherme

**Comment by jasonkuhrt** [comment]
Hey @guipena We will be releasing a new version of the platform possibly next week or the there after that will address this and other issues. We will post back once its released.

**Comment by guipena** [comment]
Thank you!

Just FYI we already got the cloud module to work before. Just 2 weeks ago, we were sending data from the cloud to our heroku app, but now it's not responding anymore. : /

Cheers, Guilherme

**Comment by jasonkuhrt** [comment]
@guipena We are aiming for a release tomorrow and releases thereafter will be more frequent and agile.

**Comment by genechan** [comment]
Hi,
Has there any been update about the release? 
I'm still have not been able to get any data into my heroku app yet from the POST request from my cloudbit.

Thanks
Gene

**Comment by jasonkuhrt** [comment]
Hey @genechan We have been rolling out our updates and creating the new docs site. If its not working already then it should be very soon. Most likely we have to make some tweaks to our seed server.

Thanks for your patience and here is a sneak peak of the in progress docs:

![screen shot 2014-11-13 at 5 41 13 pm](https://cloud.githubusercontent.com/assets/284476/5038253/ab223996-6b5c-11e4-95a9-c1995370c824.png)

The repo is public.

**Comment by genechan** [comment]
This is awesome, Thanks!!

**Comment by jasonkuhrt** [comment]
@genechan Everything should be working again. Can you please take a look at the updated demo and close this issue if everything is good on your end. If there is an issue let us know; its working on our end.

**Comment by Penrock1547** [comment]
@jasonkuhrt - I think I'm getting a null body on POST after the latest release (nicely handles the GET root now..thanks!).  

I have a button module only attached to the ClouldBit.  

This repeats in the Heroku logs:

> 2015-01-08T02:20:25.438765+00:00 heroku[router]: at=info method=POST path="/" host=cloudbit-reader.herokuapp.com request_id=xxxx fwd=xxxx dyno=web.1 connect=2ms service=2ms status=200 bytes=137
> 
> 2015-01-08T02:20:25.435513+00:00 app[web.1]: received POST: null

**Comment by jasonkuhrt** [comment]
@Penrock1547 your webhook `subscriber_id` needs to be set to `<your-app>.herokuapp.com` not the `heroku.com` variant. Does this relate to your case?

**Comment by jasonkuhrt** [comment]
@stresslimit It would be nice if our webhook POST would follow redirects. Something to consider for the future.

**Comment by Penrock1547** [comment]
@jasonkuhrt  I believe this is setup correctly,

In the result of GET on subscribers i get subscriber_id is "subscriber_id":"http://cloudbit-reader.heroku.com" which is my app.

**Comment by jasonkuhrt** [comment]
@Penrock1547 Unfortunately that's wrong actually. You need to use: `http://cloudbit-reader.herokuapp.com`. The one you are using is actually a `301` to `herokuapp.com`.

**Comment by Penrock1547** [comment]
ahh...my bad... Thanks...I fixed that and its working great now.  Gotta say...I'm pretty impressed with the cloudBit. I love it!  Thanks for all the help!

**Comment by jasonkuhrt** [comment]
@Penrock1547 Thanks for your patience and feedback on this issue. Glad to hear its working!

**Comment by jasonkuhrt** [comment]
Going to close now : )
